---
abstract: "Object which stringifies to space+backspace (\" \\b\")"
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-SpaceBackStr
requires:
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Object-SpaceBackStr/
  repository: http://github.com/sharyanto/perl-Object-SpaceBackStr
version: 0.02
